name: Build and Release Python EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取所有标签
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build EXE files
      run: |
        pyinstaller --onefile sender.py
        pyinstaller --onefile receiver.py
        
    - name: Get tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')  # 只在有标签时创建 release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # 使用触发构建的标签名
        files: |
          dist/sender.exe
          dist/receiver.exe
        body: |
          ### 系统要求
          - Windows 7 或更高版本
          
          ### 注意事项
          直接运行 exe 文件即可
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts (for manual trigger)
      if: github.event_name == 'workflow_dispatch'  # 只在手动触发时上传 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: |
          dist/sender.exe
          dist/receiver.exe
